Web/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import UserViewSet, InformationViewSet

# app_name = "api"

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'informations', InformationViewSet)

urlpatterns = [
    path('', include(router.urls)), 
]

Web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_admin/', include('site_admin.urls')),
    
    path('api/', include('api.urls')),

    path('api-auth/', include('rest_framework.urls')), # API 화면에 Log In/Out 표시
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/site_admin/urls.py
from django.urls import path
from . import views

app_name = "site_admin"

urlpatterns = [
    path("", views.MainView.as_view(), name="main"),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
    path("liveCam/", views.liveCamView.as_view(), name="liveCam"),
    path("setting/", views.SettingView.as_view(), name="setting"),
    path("detail/", views.DetailView.as_view(), name="detail"),
    
    path("test/", views.TestView.as_view(), name="test"),   
]

Web/임시/web_admin/admin/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_admin/', include('site_admin.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/site_admin/models.py
from django.db import models

# Create your models here.

Web/임시/web_admin/admin/site_admin/models.py
from django.db import models

# Create your models here.

Web/site_admin/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
import requests
from api.models import Information

class MainView(View):
    template_name = "site_admin/main_.html"

    def get(self, request):
        return render(request, self.template_name)
    
class StatisticsView(View):
    template_name = "site_admin/statistics.html"
    def get(self, request):
        return render(request, self.template_name)

class liveCamView(View):
    template_name = "site_admin/liveCam.html"

    def get(self, request):
        return render(request, self.template_name)

class DetailView(View):
    template_name = "site_admin/detail.html"
    def get(self, request):
        return render(request, self.template_name)
    
# class SettingView(View):
#     template_name = "site_admin/setting.html"

#     def get(self, request):
#         # 게시물 목록 출력
#         postList = Information.objects.order_by('-dateTime')
#         context = {'postList': postList}
#         return render(request, 'site_admin/setting.html', context)

class SettingView(View):
    template_name = "site_admin/setting.html"

    def get(self, request):
        return render(request, self.template_name)
    
class TestView(View):
    template_name = "site_admin/test.html"

    def get(self, request):
        return render(request, self.template_name)


def test(request):
    if request.method == 'POST':
        image = request.FILES.get('camera-image')
        CameraImage.objects.create(image=image)
    images = CameraImage.objects.all()
    context = {
        'images': images
    }
    return render(request, 'camera_view.html', context)

def index(request):
    # 게시물 목록 출력
    postList = Information.objects.order_by('-dateTime')
    context = {'postList': postList}
    return render(request, 'site_admin/setting.html', context)

Web/임시/web_admin/admin/site_admin/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
import requests

class MainView(View):
    template_name = "site_admin/main_.html"

    def get(self, request):
        return render(request, self.template_name)
    
class StatisticsView(View):
    template_name = "site_admin/statistics.html"
    def get(self, request):
        return render(request, self.template_name)

class liveCamView(View):
    template_name = "site_admin/liveCam.html"

    def get(self, request):
        return render(request, self.template_name)

class DetailView(View):
    template_name = "site_admin/detail.html"
    def get(self, request):
        return render(request, self.template_name)
    
# class SettingView(View):
#     template_name = "site_admin/setting.html"

#     def get(self, request):
#         # 게시물 목록 출력
#         postList = Information.objects.order_by('-dateTime')
#         context = {'postList': postList}
#         return render(request, 'site_admin/setting.html', context)

class SettingView(View):
    template_name = "site_admin/setting.html"

    def get(self, request):
        return render(request, self.template_name)
    
class TestView(View):
    template_name = "site_admin/test.html"

    def get(self, request):
        return render(request, self.template_name)


def test(request):
    if request.method == 'POST':
        image = request.FILES.get('camera-image')
        CameraImage.objects.create(image=image)
    images = CameraImage.objects.all()
    context = {
        'images': images
    }
    return render(request, 'camera_view.html', context)
'''
def index(request):
    # 게시물 목록 출력
    postList = Information.objects.order_by('-dateTime')
    context = {'postList': postList}
    return render(request, 'site_admin/setting.html', context)
'''

Web/임시/web_admin/admin/templates/site_admin/bener.html
<div class="top">
    <a href="{% url 'site_admin:main' %}"><img src="/../static/images/LOGO.svg" 
    style="vertical-align: middle;border-style: none;"/></a>
    <span class = 'new'>신규알람 0건
        <img class='bell' src="\web_admin\admin\static\images\bell.svg"/>
    </span>
</div>
<div class="side">
    <a href="{% url 'site_admin:main' %}">
        <button class="dashboard">
            <div class="name"></div>
            <span class="yet_click">대시보드</span>
        </button>
    </a>

    <a href="{% url 'site_admin:detail' %}">
        <button class="total">
            <div class="name"></div>
            <span class="yet_click">전체내역</span>
        </button>
    </a>

    <a href="{% url 'site_admin:liveCam' %}">
        <button class="livecam">
            <div class="name"></div>
            <span class="yet_click">LIVECAM</span>
        </button>
    </a>    

    <a href="{% url 'site_admin:statistics' %}">
        <button class="statistic">
            <div class="name"></div>
            <span class="yet_click">통계</span>
        </button>
    </a>      

    <a href="{% url 'site_admin:setting' %}">
        <button class="setting">
            <div class="name"></div>
            <span class="now_click">관리자설정</span>
        </button>
    </a>
</div>

Web/임시/web_admin/admin/templates/site_admin/detail.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Spoqa+Han+Sans+Neo&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/detail.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/topleft.css' %}"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <!-- <script defer type="module" src="{% static 'js/detail.js' %}"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{% static 'js/detail.js' %}"></script>
        <script src="/static/js/topalarmicon.js"></script>
        <script src="/static/js/accept_delete.js"></script>
        <title>오키도기</title>
    </head>

    <body>
        <div class="v20_125">
            <div class="top">
                <a href="{% url 'site_admin:main' %}"><img src="/../static/images/LOGO.svg" 
				style="vertical-align: middle;border-style: none;"/></a>
                <span class = 'new'>신규알람 6건
                    <img class='bell' src="\web_admin\admin\static\images\bell.svg"/>
                </span>
            </div>
            <div class="side">
                <a href="{% url 'site_admin:main' %}">
                    <button class="dashboard">
                        <div class="name"></div>
                        <span class="yet_click">대시보드</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:detail' %}">
                    <button class="total">
                        <div class="name"></div>
                        <span class="now_click">전체내역</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:liveCam' %}">
                    <button class="livecam">
                        <div class="name"></div>
                        <span class="yet_click">LIVECAM</span>
                    </button>
                </a>    

                <a href="{% url 'site_admin:statistics' %}">
                    <button class="statistic">
                        <div class="name"></div>
                        <span class="yet_click">통계</span>
                    </button>
                </a>      

                <a href="{% url 'site_admin:setting' %}">
                    <button class="setting">
                        <div class="name"></div>
                        <span class="yet_click">관리자설정</span>
                    </button>
                </a>
            </div>
            <div class="content">
                <div class="title">전체내역</div>
                <div class="main">
                    <!-- ----------------------- 테이블 시작 ------------------------------- -->
                    <div class="table_container">
                        <div class="recent" >
                            <table id="table_recent">
                                <thead>  
                                    <tr>
                                        <th scope="col" id="col">화면</th>
                                        <th scope="col" id="col">위치</th>
                                        <th scope="col" id="col">시간</th>
                                        <th scope="col" id="col">대응</th>
                                    </tr>
                                </thead>
                                <tbody id="info_table_tbody">
                                </tbody>
                            </table>                        
                        </div>
                    

                        <!-- -------------row가 6개 이상 생기면 table 하나 더 생김---------------------- -->
                        <div class="recent2" > 
                            <table id="table_recent">
                                <thead>  
                                    <tr>
                                        <th scope="col" id="col">화면</th>
                                        <th scope="col" id="col">위치</th>
                                        <th scope="col" id="col">시간</th>
                                        <th scope="col" id="col">대응</th>
                                    </tr>
                                </thead>
                                <tbody id="info_table_tbody2">

                                </tbody>
                            </table>    
                        </div>
                    </div>
                </div>
                <div id='page'>
                    <div id="pagination"></div>
                </div>
            </div>

        </div>
    </body>
</html>

Web/임시/web_admin/admin/templates/site_admin/liveCam.html
{% load static %}
<!DOCTYPE html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Spoqa+Han+Sans+Neo&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/livecam.css' %}"/>
        <script defer type="module" src="{% static 'js/livecam.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <script src="/static/js/topalarmicon.js"></script>
        <title>오키도기</title>
    </head>
    <body>

        <!-- 고정바 -->
        <div class="v20_125">
            <div class="top">
                <a href="{% url 'site_admin:main' %}"><img src="/../static/images/LOGO.svg" 
				style="vertical-align: middle;border-style: none;"/></a>
                <span class = 'new'>신규알람 6건
                    <img class='bell' src="\web_admin\admin\static\images\bell.svg"/>
                </span>
            </div>
            
            <div class="side">
                <a href="{% url 'site_admin:main' %}">
                    <button class="dashboard">
                        <div class="name"></div>
                        <span class="yet_click">대시보드</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:detail' %}">
                    <button class="total">
                        <div class="name"></div>
                        <span class="yet_click">전체내역</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:liveCam' %}">
                    <button class="livecam">
                        <div class="name"></div>
                        <span class="now_click">LIVECAM</span>
                    </button>
                </a>    

                <a href="{% url 'site_admin:statistics' %}">
                    <button class="statistic">
                        <div class="name"></div>
                        <span class="yet_click">통계</span>
                    </button>
                </a>      

                <a href="{% url 'site_admin:setting' %}">
                    <button class="setting">
                        <div class="name"></div>
                        <span class="yet_click">관리자설정</span>
                    </button>
                </a>
            </div>

        <!-- CAM  -->
            <div class="content">
                <div class="title">LIVECAM</div>
                <div class="main">
                    <div class="cam_box_1">
                        <div class="cam_num_1">CAM 01</div>
                        <div class="cam_video_1">
                            <img src="http://43.202.121.88/api/video" alt ='video' width="400" height="250">
                        </div>
                    </div>

                    <div class="cam_box_2">
                        <div class="cam_num_2">CAM 02</div>
                        <div class="cam_video_2">
                            <video id="video" width="400" height="250" autoplay></video>
                        </div> 
                    </div>

                    <div class="cam_box_3">
                        <div class="cam_num_3">CAM 03</div>
                        <div class="cam_video_3">
                            <video id="video" width="400" height="250" autoplay></video>
                        </div> 
                    </div>

                    <div class="cam_box_4">
                        <div class="cam_num_4">CAM 04</div>
                        <div class="cam_video_4">
                            <video id="video" width="400" height="250" autoplay></video>
                        </div> 
                    </div>

                    <div class="cam_box_5">
                        <div class="cam_num_5">CAM 05</div>
                        <div class="cam_video_5">
                            <video id="video" width="400" height="250" autoplay></video>
                        </div> 
                    </div>

                    <div class="cam_box_6">
                        <div class="cam_num_6">CAM 06</div>
                        <div class="cam_video_6">
                            <video id="video" width="400" height="250" autoplay></video>
                        </div> 
                    </div>

                </div>
            </div>
        </div>
    </body>

Web/임시/web_admin/admin/templates/site_admin/main.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script defer type="module" src="{% static 'js/main.js' %}"></script>

    <title>Document</title>
</head>

<body>
    <div class="top-bar">
        <button class="top-button" id="live-cam"> 
            <a href="{% url 'site_admin:liveCam' %}">LIVE <span>CAM</span></a>
        </button>

        <button class="top-button" id="write">
            <a href="{% url 'site_admin:setting' %}">안내 멘트 작성</a>
        </button> 

        <button class="top-button" id="record">
            <a href="{% url 'site_admin:detail' %}">기록</a>
        </button>
    </div>

    <div class="mid-bar"> 
        <div class="mid-buttons">
            <button class="mid-button" id="all">ALL</button>
            <button class="mid-button" id="today">오늘</button>
        </div>  
        <h1>알림 횟수 <span>10회</span></h1>
    </div>

    <div class="chart">
        그래프 들어가자
    </div>
</body>

</html>

Web/임시/web_admin/admin/templates/site_admin/statistics.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Spoqa+Han+Sans+Neo&display=swap" rel="stylesheet" />

        <!--chart js-->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <!--date picker bootstrap-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />

        <link rel="stylesheet" href="{% static 'css/statistics.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.ko.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <!-- <script defer type="module" src="{% static 'js/statistics.js' %}"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/danfojs@1.1.2/lib/bundle.min.js"></script> 
        <script src="{% static 'js/statistics.js' %}"></script>
        <script src="/static/js/topalarmicon.js"></script>

        <title>통계</title>
    </head>
    <body>
        <div class="v20_125">
            <div class="top">
                <a href=""><img src="/../static/images/LOGO.svg" 
				style="vertical-align: middle;border-style: none;"/></a>
                <span class = 'new'>신규알람 6건
                    <img class='bell' src="\web_admin\admin\static\images\bell.svg"/>
                </span>
            </div>
            <div class="side">
                <a href="{% url 'site_admin:main' %}">
                    <button class="dashboard">
                        <div class="name"></div>
                        <span class="yet_click">대시보드</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:detail' %}">
                    <button class="total">
                        <div class="name"></div>
                        <span class="yet_click">전체내역</span>
                    </button>
                </a>

                <a href="{% url 'site_admin:liveCam' %}">
                    <button class="livecam">
                        <div class="name"></div>
                        <span class="yet_click">LIVECAM</span>
                    </button>
                </a>    

                <a href="{% url 'site_admin:statistics' %}">
                    <button class="statistic">
                        <div class="name"></div>
                        <span class="now_click">통계</span>
                    </button>
                </a>        

                <a href="{% url 'site_admin:setting' %}">
                    <button class="setting">
                        <div class="name"></div>
                        <span class="yet_click">관리자설정</span>
                    </button>
                </a>
            </div>
            <div class="content">
                <div class="title">통계</div>
                <div class="main">
                    <!----------------------------------------------- 시간별----------------------------------------- -->
                    <div class="time_count">
                        <div id="subtitle">
                            <span>시간별 알림 횟수</span>
                            <div class="inputs">
                                <span style="font-size: 14px;">날짜 변경</span>
                                <form>
                                    <div class="form-group">
                                        <input value="TODAY    " type="text" class="form-control" id="datepicker1" style="width:114px; background-image: url(https://img.icons8.com/color/48/calendar--v1.png);
                                        background-position: 7px center; background-repeat: no-repeat; background-size: 20px;" control-id="ControlID-1">
                                    </div>
                                </form>
                            </div>
                            <script> //calendar script </script>
                        </div>
                        <div id="chart_container_time">
                            <canvas id="timechart"></canvas>
                        </div>
                    </div>
                    <!----------------------------------------------- 요일별----------------------------------------- -->
                    <div class="day_count">
                        <div id="subtitle">
                            <span>요일별 알림 횟수</span>
                            <div class="inputs">
                                <span style="font-size: 14px;">주차 변경</span>
                                <form>
                                    <div class="form-group">
                                        <input value="SUNDAY ~ MONDAY    " type="text" class="form-control" id="datepicker2" style="width:200px; background-image: url(https://img.icons8.com/color/48/calendar--v1.png);
                                        background-position: 7px center; background-repeat: no-repeat; background-size: 20px;" control-id="ControlID-1">
                                    </div>
                                </form>
                            </div>
                            <script> //calandar script </script>
                        </div>
                        <div id="chart_container_day">
                            <canvas id="daychart"></canvas>
                        </div>
                    </div>
                    <!----------------------------------------------- 월별----------------------------------------- -->
                    <div class="month_count">
                        <div id="subtitle">
                            <span>월별 알림 횟수</span>
                            <div class="inputs">
                                <span style="font-size: 14px;">연도 변경</span>
                                <form>
                                    <div class="form-group">
                                        <input value="2023" type="text" class="form-control" id="datepicker3" style="width:77px; background-image: url(https://img.icons8.com/color/48/calendar--v1.png);
                                        background-position: 7px center; background-repeat: no-repeat; background-size: 20px;" control-id="ControlID-1">
                                    </div>
                                </form>
                            </div>
                            
                            <script> //calendar script</script>
                        </div>
                        <div id="chart_container_month">
                            <canvas id="monthchart"></canvas>
                        </div>
                    </div>

                    <!----------------------------------------------- 우선순위----------------------------------------- -->
                    <div class="small_boxes">
                        <!-------------------------- 우선위치---------------------------------->
                        <div class="main_place">
                            <div id="subtitle">단속 우선 위치</div>
                            <ul id="top-container">
                                <li class="ranking first">
                                    <div class="nums">1</div>
                                    <div class="circle" style="background: #30C9CF;"></div>
                                    <span class="top_text">(전)0110P_032</span>
                                </li>
                                <li class="ranking second">
                                    <div class="nums">2</div>
                                    <div class="circle" style="background: #3CCEA0;"></div>
                                    <span class="top_text">(전)0110P_032</span>
                                </li>
                                <li class="ranking third">
                                    <div class="nums">3</div>
                                    <div class="circle" style="background: #9CC1F6;"></div>
                                    <span class="top_text">(전)0110P_032</span>
                                </li>

                            </ul>
                        </div>
        
    
                        <!-------------------------- 우선시간---------------------------------->
                        <div class="main_time">
                            <div id="subtitle">단속 우선 시간</div>
                            <ul id="top-container">
                                <li class="ranking first">
                                    <div class="nums">1</div>
                                    <span class="top_text">PM3~4</span>
                                </li>
                                <li class="ranking second">
                                    <div class="nums">2</div>
                                    <span class="top_text">PM3~4</span>
                                </li>
                                <li class="ranking third">
                                    <div class="nums">3</div>
                                    <span class="top_text">PM3~4</span>
                                </li>

                            </ul>
                        </div>


                        
                    </div>   
                </div>




                    
                </div>
            </div>
            
        </div>
    </body>
</html>

Web/임시/web_admin/admin/templates/site_admin/test.html
{% load static %}
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
    <script src="{% static 'js/test.js' %}"></script>
</head>

<body>
  <table>
    <thead>
      <tr>
        <th scope="col">CAM</th>
        <th scope="col">IMAGE</th>
        <th scope="col">시간</th>
        <th scope="col">위치</th>
        <th scope="col">정보</th>
        <th scope="col">대응</th>
      </tr>
    </thead>
    <tbody id="info_table_tbody">
    </tbody>
  </table>
</body>